version: "3"

services:
  app:
    container_name: go
    build:
      context: .
    ports:
      - "5000:5000"
  # mongodb:
    # container_name: mongodb
    # image: mongo:5.0
    # ports:
      # - "27017:27017"
